name: CustomItems
main: com.github.neapovil.customitems.CustomItems
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/Neapovil/customitems
depend:
  - CommandAPI
permissions:
  customitems.command:
    default: true
  customitems.command.admin:
    default: op
